package View;
import Controller.*;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Karol Pitera
 */
public class InitFrame extends javax.swing.JFrame {
    
    private String name;
    private String difficultyLevel;
    private GameController controller;

      /**
     * Creates new form InitFrame
     */
    public InitFrame() {
        initComponents();
        setLocationRelativeTo(null); // This will center the frame on the screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterButton1 = new javax.swing.JButton();
        jLabelName = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        jLabelMessageLevel = new javax.swing.JLabel();
        choseLevelComboBox = new javax.swing.JComboBox<>();
        enterButton = new javax.swing.JButton();

        enterButton1.setMnemonic('E');
        enterButton1.setText("Enter");
        enterButton1.setToolTipText("Set your choice");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabelName.setText("Type in your name: ");

        userName.setText("userName");
        userName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameActionPerformed(evt);
            }
        });

        jLabelMessageLevel.setText("Check difficulty level:");

        choseLevelComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Easy", "Medium", "Hard", " " }));
        choseLevelComboBox.setToolTipText("");
        choseLevelComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choseLevelComboBoxActionPerformed(evt);
            }
        });

        enterButton.setMnemonic('E');
        enterButton.setText("Enter");
        enterButton.setToolTipText("Set your choice");
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMessageLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(choseLevelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(enterButton)
                .addGap(0, 160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMessageLevel)
                    .addComponent(choseLevelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(enterButton)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameActionPerformed

    private void choseLevelComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choseLevelComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choseLevelComboBoxActionPerformed

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
                                                  
        // Get the user input from text field and combo box
        name = userName.getText();  // Get user name from text field
        difficultyLevel = (String) choseLevelComboBox.getSelectedItem();  // Get selected difficulty level
    
        // Validate inputs and notify via controller
        if (name.isEmpty()) {
            new MessageFrame("Please enter your name.");
        } else if (difficultyLevel == null || difficultyLevel.trim().isEmpty()) {
            new MessageFrame("Please select a difficulty level.");
        } else {
            try {
                // If inputs are valid, delegate the start to the controller
                controller.startGame(name, difficultyLevel);
            } catch (InvalidDifficultyLevelException ex) {
                Logger.getLogger(InitFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();  // Close the InitFrame (optional, based on your flow)
        }
    
    }//GEN-LAST:event_enterButtonActionPerformed

    
// Getters for the inputs, to be used by the controller
    public String downloadName() {
        return name;
    }
    
    public String downloadDifficultyLevel() {
        return difficultyLevel;
    }
    
    // Setter for the controller
    public void setController(GameController controller) {
        this.controller = controller;
    }
    
    public  GameController getController() {
        return this.controller;
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> choseLevelComboBox;
    private javax.swing.JButton enterButton;
    private javax.swing.JButton enterButton1;
    private javax.swing.JLabel jLabelMessageLevel;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
